// <auto-generated />
using CalcYaWorthWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalcYaWorthWebAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190812224156_RemovedAppSettings")]
    partial class RemovedAppSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalcYaWorthWebAPI.Models.Asset", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Description");

                    b.Property<long>("TimeCreated");

                    b.Property<long>("TimeModified");

                    b.Property<int>("UserId");

                    b.HasKey("Identifier");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("CalcYaWorthWebAPI.Models.Liability", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Description");

                    b.Property<long>("TimeCreated");

                    b.Property<long>("TimeModified");

                    b.Property<int>("UserId");

                    b.HasKey("Identifier");

                    b.HasIndex("UserId");

                    b.ToTable("Liabilities");
                });

            modelBuilder.Entity("CalcYaWorthWebAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyIsoCode")
                        .HasMaxLength(3);

                    b.Property<string>("Username")
                        .HasMaxLength(255);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CalcYaWorthWebAPI.Models.Asset", b =>
                {
                    b.HasOne("CalcYaWorthWebAPI.Models.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CalcYaWorthWebAPI.Models.Liability", b =>
                {
                    b.HasOne("CalcYaWorthWebAPI.Models.User", "User")
                        .WithMany("Liabilities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
